version: 2

project_name: farm-manager

builds:
  - id: farm-manager
    main: ./cmd/farm-manager
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - darwin
      - windows
    goarch:
      - amd64
      # - arm64
    flags:
      - -trimpath
      - -mod=vendor
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: archives
    ids:
      - farm-manager
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - db/migrations/*.sql
      - public/**/*

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

release:
  github:
    owner: cr1cr1
    name: farm-manager
  draft: false
  prerelease: auto
